Issue 285 - Script install_unattended_upgrade_tools in not Idempotent (#5)
* Make script idenpotent
* Group apticron config changes together
* Improve script comments and log
* Implement suggestions from shellcheck.net

diff --git a/ubuntu-18.04/install_unattended_upgrade_tools b/ubuntu-18.04/install_unattended_upgrade_tools
--- a/ubuntu-18.04/install_unattended_upgrade_tools
+++ b/ubuntu-18.04/install_unattended_upgrade_tools
@@ -1,8 +1,11 @@
 #!/bin/bash
 #
 # Install unattended upgrade tools on Ubuntu 18.04.
-# This script must be run as root (ex.: sudo sh ./[script_name]).
-# Style Guide: https://google.github.io/styleguide/shellguide.html
+# Notes
+#   This script must be run as root (ex.: sudo sh ./[script_name]).
+#   This script is designed to be idempotent.
+# Style Guide
+#   https://google.github.io/styleguide/shellguide.html
 
 # Parameters: all manadatory and must be prefix with "--" on command line.
 declare -A parameters=( \
@@ -22,6 +25,76 @@ readonly UNATTENDED_UPGRADES_CONF_FILE_PATH="/etc/apt/apt.conf.d/50unattended-up
 # Functions
 source ./logger.sh
 source ./utils.sh
+
+#######################################
+# Update or append a parameter to a file if missing.
+# Arguments:
+#   1) Parameter to set, text string.
+#   2) Value to set, text string.
+#   3) File to update, file path
+# Outputs:
+#   Writes log messages to STDOUT.
+#   Writes error messages to STDERR.
+#######################################
+function update_or_append() {
+  local parameter="$1"
+  local value="$2"
+  local file_path="$3"
+
+  case $(grep -c "^${parameter}" "${file_path}") in
+  0)
+    logger::info "Parameter \"${parameter}\" not found in \"${file_path}\". Appending it..."
+    echo "${parameter} \"${value}\";" >> "${file_path}"
+    ;;
+  1)
+    logger::info "Parameter \"${parameter}\" found in \"${file_path}\". Updating it..."
+    sed -i -e "s|^{parameter}|{parameter} \"${value}\";|g" "${file_path}"
+    ;;
+  *)
+    logger::error "More than one line matched the search criteria. Aborting."
+    exit 1
+    ;;
+  esac
+}
+
+#######################################
+# Update or insert a parameter to a file at a specific location if missing.
+# Arguments:
+#   1) Parameter to set, text string.
+#   2) Value to set, text string.
+#   3) Insertion point, text string
+#   4) File to update, file path
+# Outputs:
+#   Writes log messages to STDOUT.
+#   Writes error messages to STDERR.
+#######################################
+function update_or_insert() {
+  local parameter="$1"
+  local value="$2"
+  local insertion_point="$3"
+  local file_path="$4"
+
+  case $(grep -c "^${parameter}" "${file_path}") in
+    0)
+      logger::info "Parameter \"${parameter}\" not found in \"${file_path}\"."
+      if grep -q "^${insertion_point}" "${file_path}"; then
+        logger::info "Insertion point \"${insertion_point}\" found. Inserting parameter under the insertion point..."
+        sed -i -e "/^${insertion_point}.*$/a ${parameter} = ${value}" "${file_path}"
+      else
+        logger::info "Insertion point \"${insertion_point}\" not found in \"${file_path}\". Aborting."
+        exit 1
+      fi
+      ;;
+    1)
+      logger::info "Parameter \"${parameter}\" found in \"${file_path}\". Updating it..."
+      sed -i -e "s/^${parameter}.*$/${parameter} = ${value}/g" "${file_path}"
+      ;;
+    *)
+      logger::error "More than one line matched the search criteria. Aborting."
+      exit 1
+      ;;
+  esac
+}
 
 function main() {
   utils::set_exit_trap
@@ -56,73 +129,77 @@ function main() {
   logger::action "Enabling OS updates..."
   sed -i -e "s|^//\([[:blank:]]*\"\${distro_id}:\${distro_codename}-updates\";\)$|  \1|g" "${UNATTENDED_UPGRADES_CONF_FILE_PATH}"
 
-  logger::action "Setting Unattended-Upgrade::Mail parameter..."
+  logger::action "Setting \"Unattended-Upgrade::Mail\" parameter to \"${parameters[server_admin_email]}\"..."
   sed -i -e "s|^//\(Unattended-Upgrade::Mail\) .*$|\1 \"${parameters[server_admin_email]}\";|g" "${UNATTENDED_UPGRADES_CONF_FILE_PATH}"
 
-  logger::action "Enabling Unattended-Upgrade::Remove-Unused-Kernel-Packages..."
+  logger::action "Enabling \"Unattended-Upgrade::Remove-Unused-Kernel-Packages\"..."
   sed -i -e "s|^//\(Unattended-Upgrade::Remove-Unused-Kernel-Packages\) .*$|\1 \"true\";|g" "${UNATTENDED_UPGRADES_CONF_FILE_PATH}"
 
-  logger::action "Enabling Unattended-Upgrade::Remove-Unused-Dependencies..."
+  logger::action "Enabling \"Unattended-Upgrade::Remove-Unused-Dependencies\"..."
   sed -i -e "s|^//\(Unattended-Upgrade::Remove-Unused-Dependencies\) .*$|\1 \"true\";|g" "${UNATTENDED_UPGRADES_CONF_FILE_PATH}"
 
-  logger::action "Enabling Unattended-Upgrade::Automatic-Reboot..."
+  logger::action "Enabling \"Unattended-Upgrade::Automatic-Reboot\"..."
   sed -i -e "s|^//\(Unattended-Upgrade::Automatic-Reboot\) .*$|\1 \"true\";|g" "${UNATTENDED_UPGRADES_CONF_FILE_PATH}"
 
-  logger::action "Setting Unattended-Upgrade::Automatic-Reboot-Time..."
+  logger::action "Setting \"Unattended-Upgrade::Automatic-Reboot-Time\" to \"${parameters[server_reboot_utc_time]}\"..."
   sed -i -e "s|^//\(Unattended-Upgrade::Automatic-Reboot-Time\) .*$|\1 \"${parameters[server_reboot_utc_time]}\";|g" "${UNATTENDED_UPGRADES_CONF_FILE_PATH}"
 
   #############################################################################
 
   logger::title "Configure Aptitude (apt)"
 
-  logger::action "Setting APT::Periodic::Download-Upgradeable-Packages parameter..."
-  echo "APT::Periodic::Download-Upgradeable-Packages \"1\";" >> "${AUTO_UPGRADES_CONF_FILE_PATH}"
+  logger::action "Setting \"APT::Periodic::Download-Upgradeable-Packages\" parameter to \"1\"..."
+  # This parameter is not present in the original file but will be there in subsequent script runs.
+  update_or_append "APT::Periodic::Download-Upgradeable-Packages" "1" "${AUTO_UPGRADES_CONF_FILE_PATH}"
 
-  logger::action "Setting APT::Periodic::AutocleanInterval parameter..."
-  echo "APT::Periodic::AutocleanInterval \"7\";" >> "${AUTO_UPGRADES_CONF_FILE_PATH}"
-
-  logger::action "Setting Apticron EMAIL parameter..."
-  sed -i -e "s/^\(EMAIL=\).*$/\1\"${parameters[server_admin_email]}\"/g" "${APTICRON_CONF_FILE_PATH}"
+  logger::action "Setting \"APT::Periodic::AutocleanInterval\" parameter to \"7\"..."
+  # This parameter is not present in the original file but will be there in subsequent script runs.
+  update_or_append "APT::Periodic::AutocleanInterval" "7" "${AUTO_UPGRADES_CONF_FILE_PATH}"
 
   #############################################################################
 
   logger::title "Configure Apticron"
 
-  logger::action "Setting Apticron SYSTEM parameter..."
+  logger::action "Setting \"EMAIL\" parameter to \"${parameters[server_admin_email]}\"..."
+  sed -i -e "s/^\(EMAIL=\).*$/\1\"${parameters[server_admin_email]}\"/g" "${APTICRON_CONF_FILE_PATH}"
+
+  logger::action "Setting \"SYSTEM\" parameter to \"${parameters[server_resource_name]}\"..."
   sed -i -e "s/^\(SYSTEM=\).*$/\1\"${parameters[server_resource_name]}\"/g" "${APTICRON_CONF_FILE_PATH}"
 
-  logger::action "Setting Apticron NOTIFY_HOLDS parameter..."
+  logger::action "Disabling \"NOTIFY_HOLDS\" parameter..."
   sed -i -e "s/^\(NOTIFY_HOLDS=\).*$/\1\"0\"/g" "${APTICRON_CONF_FILE_PATH}"
 
-  logger::action "Setting Apticron NOTIFY_NEW parameter..."
+  logger::action "Disabling \"NOTIFY_NEW\" parameter..."
   sed -i -e "s/^\(NOTIFY_NEW=\).*$/\1\"0\"/g" "${APTICRON_CONF_FILE_PATH}"
 
-  logger::action "Setting Apticron NOTIFY_NO_UPDATES parameter..."
+  logger::action "Enabling \"NOTIFY_NO_UPDATES\" parameter..."
   sed -i -e "s/^\(NOTIFY_NO_UPDATES=\).*$/\1\"0\"/g" "${APTICRON_CONF_FILE_PATH}"
 
-  logger::action "Setting Apticron CUSTOM_SUBJECT parameter..."
+  logger::action "Setting \"CUSTOM_SUBJECT\" parameter to '[apticron] \$SYSTEM: \$NUM_PACKAGES package update(s)'..."
   sed -i -e "s/^# \(CUSTOM_SUBJECT=\)\"\".*$/\1'[apticron] \$SYSTEM: \$NUM_PACKAGES package update(s)'/g" "${APTICRON_CONF_FILE_PATH}"
 
-  logger::action "Setting Apticron CUSTOM_NO_UPDATES_SUBJECT parameter..."
+  logger::action "Setting \"CUSTOM_NO_UPDATES_SUBJECT\" parameter to '[apticron] \$SYSTEM: no updates'..."
   sed -i -e "s/^# \(CUSTOM_NO_UPDATES_SUBJECT=\)\"\".*$/\1'[apticron] \$SYSTEM: no updates'/g" "${APTICRON_CONF_FILE_PATH}"
 
   #############################################################################
 
   logger::title "Configure Postfix"
 
-  logger::action "Setting Postfix myhostname parameter..."
+  logger::action "Setting \"myhostname\" parameter to \"${parameters[server_fqdn]}\"..."
   sed -i -e "s/^\(myhostname =\).*$/\1 ${parameters[server_fqdn]}/g" "${POSTFIX_CONF_FILE_PATH}"
 
-  logger::action "Setting Postfix myorigin parameter..."
+  logger::action "Setting \"myorigin\" parameter to \"\$myhostname\"..."
+  # This setting may not be present in file. If it is, we update it.
   sed -i -e "s/^\(myorigin =\).*$/\1 \$myhostname/g" "${POSTFIX_CONF_FILE_PATH}"
 
-  logger::action "Setting Postfix relayhost parameter..."
+  logger::action "Setting \"relayhost\" parameter to \"${parameters[smtp_server_fqdn]}:${parameters[smtp_server_port]}\"..."
   sed -i -e "s/^\(relayhost =\).*$/\1 ${parameters[smtp_server_fqdn]}:${parameters[smtp_server_port]}/g" "${POSTFIX_CONF_FILE_PATH}"
 
-  logger::action "Adding Postfix smtp_tls_security_level parameter..."
-  sed -i -e "/^smtp_tls_session_cache_database = .*/a smtp_tls_security_level = encrypt" "${POSTFIX_CONF_FILE_PATH}"
+  logger::action "Setting \"smtp_tls_security_level\" parameter to \"encrypt\"..."
+  # This parameter is not present in the original file but will be there in subsequent script runs.
+  update_or_insert "smtp_tls_security_level" "encrypt" "smtp_tls_session_cache_database" "${POSTFIX_CONF_FILE_PATH}"
 
-  logger::action "Reloading Postfix configuration file..."
+  logger::action "Reloading configuration file..."
   service postfix reload
 
   #############################################################################
