Issue-881 - Server update crashes at provision time  (#6)
* Wait for other apt commands to finish before update

* Add explicit error message

diff --git a/ubuntu-18.04/upgrade_server b/ubuntu-18.04/upgrade_server
--- a/ubuntu-18.04/upgrade_server
+++ b/ubuntu-18.04/upgrade_server
@@ -14,6 +14,9 @@ source ./utils.sh
 function main() {
   utils::set_exit_trap
 
+  local waiting_time
+  local -r MAX_WAIT_TIME=60
+
   #############################################################################
 
   logger::title "Start of $0"
@@ -25,7 +28,19 @@ function main() {
   #############################################################################
 
   logger::action "Updating server package index files..."
-  apt update
+  # Fix for issue-881.
+  waiting_time=0
+  while [[ $(pgrep apt) && ${waiting_time} -lt ${MAX_WAIT_TIME} ]]; do
+    ((waiting_time++))
+    logger::info "Waiting for other apt commands to finish: ${waiting_time} sec / ${MAX_WAIT_TIME} sec...";
+    sleep 1;
+  done;
+  if [[ $(pgrep apt) ]]; then
+    logger::error "Max waiting time reached. Aborting.";
+    exit 1
+  else
+    apt update
+  fi
 
   logger::action "Upgrading all installed server packages to their latest version and apply available security patches..."
   apt upgrade -y
